/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 avatar_prototype.glb -t 
*/
"use client";
import { useAvatarMotion } from "@/hooks/useAvatarMotion";
import {
	AVATAR_MOTION_CLIPS,
	AVATAR_PLACEMENTS,
	type AvatarMotion,
	type ScenePlacement,
} from "@/lib/avatarMotion";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React, { type JSX, useLayoutEffect } from "react";
import type * as THREE from "three";
import { type GLTF, SkeletonUtils } from "three/examples/jsm/Addons.js";

type ActionName = "Waving_Mixamo" | "PCWork";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Body_1: THREE.SkinnedMesh;
		Body_2: THREE.SkinnedMesh;
		Body_3: THREE.SkinnedMesh;
		Body_4: THREE.SkinnedMesh;
		Tops: THREE.SkinnedMesh;
		Bottoms: THREE.SkinnedMesh;
		Hair: THREE.SkinnedMesh;
		mixamorigHips: THREE.Bone;
	};
	materials: {
		Body: THREE.MeshStandardMaterial;
		Face: THREE.MeshStandardMaterial;
		Eye: THREE.MeshStandardMaterial;
		Eyebrow: THREE.MeshStandardMaterial;
		Tops: THREE.MeshStandardMaterial;
		Bottoms: THREE.MeshStandardMaterial;
		Hair: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

/** モーションを切り替えるときのクロスフェード時間（秒）。 */
const FADE_DURATION = 0.4;

type AvatarPrototypeProps = JSX.IntrinsicElements["group"] & {
	/**
	 * モーションをこの時刻（秒）で止める。
	 *
	 * サムネイルの撮影で、何度撮っても同じポーズにするために使う。
	 * 指定しなければ、いつも通り再生し続ける。
	 */
	frozenTime?: number;
	/**
	 * 立ち位置を差し替える。
	 *
	 * 既定の値は部屋のどこに立つかを表したものなので、
	 * サムネイルのように部屋の外で使うときは原点などに置き直す。
	 */
	placement?: ScenePlacement;
	/**
	 * 再生するモーションを差し替える。
	 *
	 * 指定しなければクエリから読む。画面の操作で切り替えたいときに渡す。
	 */
	motion?: AvatarMotion;
};

export function AvatarPrototype({
	frozenTime,
	placement: placementOverride,
	motion: motionOverride,
	...props
}: AvatarPrototypeProps) {
	const group = React.useRef<THREE.Group>(null);
	const { scene, animations } = useGLTF("/avatar_prototype.glb");
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
	const { actions, mixer } = useAnimations(animations, group);
	const motionFromQuery = useAvatarMotion();
	const motion = motionOverride ?? motionFromQuery;
	const placement = placementOverride ?? AVATAR_PLACEMENTS[motion];

	/*
		描画の前に姿勢を確定させたいので useEffect ではなく useLayoutEffect を使う。
		useAnimations はこれより先に mixer の root を張るので、ここで actions を触ってよい。
	*/
	useLayoutEffect(() => {
		const action = actions[AVATAR_MOTION_CLIPS[motion]];
		if (!action) return;

		/*
			モーションを切り替えるときだけクロスフェードする。
			まだ何も再生していないところで fadeIn すると、重みが 0 から上がりきるまでの間
			バインドポーズ（Tポーズ）が混ざって見えてしまう。他のページから戻ってきた
			直後のように、混ぜる相手がいない場合はいきなり全体重で始める。
		*/
		const blending = Object.values(actions).some(
			(other) => other && other !== action && other.isRunning(),
		);

		action.reset();
		if (blending) action.fadeIn(FADE_DURATION);
		action.play();

		/*
			骨に姿勢を焼くのは mixer なので、最初のフレームをここで進めておく。
			次の描画を待つと、その1フレームだけTポーズやTポーズ混じりの姿勢が出る。
		*/
		mixer.update(0);

		// 止めずに薄くする。次のモーションの fadeIn と重ねてつなぐため
		return () => {
			action.fadeOut(FADE_DURATION);
		};
	}, [actions, mixer, motion]);

	/*
		撮影用にポーズを固定する。
		mixer は毎フレーム時刻を進めてしまうので、action を止めたうえで時刻を差し込み、
		その姿勢を骨に焼く。再生の待ち時間で狙うのと違い、同じ値なら必ず同じ姿勢になる。
	*/
	useLayoutEffect(() => {
		const action = actions[AVATAR_MOTION_CLIPS[motion]];
		if (!action) return;

		action.paused = frozenTime !== undefined;
		if (frozenTime === undefined) return;

		// クリップの終わりを越えると姿勢が決まらないので、末尾で止める
		action.time = Math.min(frozenTime, action.getClip().duration);
		mixer.update(0);
	}, [actions, mixer, motion, frozenTime]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene" position={placement.position} rotation={placement.rotation}>
				{/* Armature の値は glb のノードそのまま。向きの調整は上の group が持つ */}
				<group
					name="Armature"
					position={[0, 0, -0.0142]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.01}
				>
					<primitive object={nodes.mixamorigHips} />
					<group name="Body">
						<skinnedMesh
							name="Body_1"
							geometry={nodes.Body_1.geometry}
							material={materials.Body}
							skeleton={nodes.Body_1.skeleton}
						/>
						<skinnedMesh
							name="Body_2"
							geometry={nodes.Body_2.geometry}
							material={materials.Face}
							skeleton={nodes.Body_2.skeleton}
						/>
						<skinnedMesh
							name="Body_3"
							geometry={nodes.Body_3.geometry}
							material={materials.Eye}
							skeleton={nodes.Body_3.skeleton}
						/>
						<skinnedMesh
							name="Body_4"
							geometry={nodes.Body_4.geometry}
							material={materials.Eyebrow}
							skeleton={nodes.Body_4.skeleton}
						/>
					</group>
				</group>
				<skinnedMesh
					name="Tops"
					geometry={nodes.Tops.geometry}
					material={materials.Tops}
					skeleton={nodes.Tops.skeleton}
				/>
				<skinnedMesh
					name="Bottoms"
					geometry={nodes.Bottoms.geometry}
					material={materials.Bottoms}
					skeleton={nodes.Bottoms.skeleton}
				/>
				<skinnedMesh
					name="Hair"
					geometry={nodes.Hair.geometry}
					material={materials.Hair}
					skeleton={nodes.Hair.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/avatar_prototype.glb");
