/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three/examples/jsm/Addons.js";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

type GLTFResult = GLTF & {
	nodes: {
		Wall: THREE.Mesh;
		平面: THREE.Mesh;
		平面_1: THREE.Mesh;
		ローチェア: THREE.Mesh;
		AcousticGuitar_1: THREE.Mesh;
		Chair: THREE.Mesh;
		Desk_1: THREE.Mesh;
		Shelf: THREE.Mesh;
		立方体004: THREE.Mesh;
		立方体004_1: THREE.Mesh;
		ベッドクッション: THREE.Mesh;
		ベッド掛け布団: THREE.Mesh;
		ベッド枕: THREE.Mesh;
		Synthesizer001: THREE.Mesh;
		KeyboardStand: THREE.Mesh;
		ベジエカーブ006: THREE.Mesh;
		ベジエカーブ006_1: THREE.Mesh;
		円柱_1: THREE.Mesh;
		円柱_2: THREE.Mesh;
		平面012: THREE.Mesh;
		平面012_1: THREE.Mesh;
		平面010: THREE.Mesh;
		平面010_1: THREE.Mesh;
		WoodFloor001: THREE.Mesh;
	};
	materials: {
		Wall: THREE.MeshStandardMaterial;
		モニターボディ: THREE.MeshStandardMaterial;
		PC_Screen: THREE.MeshPhysicalMaterial;
		"Guitar_spruce.001": THREE.MeshStandardMaterial;
		AcousticGuitar: THREE.MeshStandardMaterial;
		Chair: THREE.MeshStandardMaterial;
		Desk: THREE.MeshStandardMaterial;
		BedBody: THREE.MeshStandardMaterial;
		BedLeg: THREE.MeshStandardMaterial;
		Cushion: THREE.MeshStandardMaterial;
		Comforter: THREE.MeshStandardMaterial;
		Synthesizer: THREE.MeshStandardMaterial;
		SyntheStand: THREE.MeshStandardMaterial;
		EucalyptusTrunk: THREE.MeshStandardMaterial;
		EucalyptusLeaf: THREE.MeshBasicMaterial;
		Planter: THREE.MeshStandardMaterial;
		Soil: THREE.MeshStandardMaterial;
		PC_Body: THREE.MeshStandardMaterial;
		"マテリアル.003": THREE.MeshStandardMaterial;
		"Floor.001": THREE.MeshPhysicalMaterial;
	};
};

export function Room(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/portfolio_room_1_1.glb",
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Wall.geometry}
				material={materials.Wall}
				rotation={[Math.PI, 0, Math.PI]}
				scale={[0.8, 1, 0.8]}
			/>
			<group position={[-0.401, 1.11, 1.3]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面.geometry}
					material={materials.モニターボディ}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面_1.geometry}
					material={materials.PC_Screen}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ローチェア.geometry}
				material={materials["Guitar_spruce.001"]}
				position={[-1.325, 0.076, -1.208]}
				rotation={[Math.PI, -0.841, Math.PI]}
				scale={[0.15, 0.022, 0.15]}
			/>
			<group position={[-0.45, 0, 0.802]} rotation={[0, -0.814, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Chair.geometry}
					material={materials.Chair}
					position={[0, 0.409, -0.043]}
				/>
			</group>
			<group position={[-0.616, 0, 1.205]} rotation={[Math.PI, 0, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Desk_1.geometry}
					material={materials.Desk}
					position={[0, 0.8, 0]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf.geometry}
				material={materials["Guitar_spruce.001"]}
				position={[-0.847, 0.469, -1.209]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<group position={[0.477, 0, -0.89]} rotation={[0, Math.PI / 2, 0]}>
				<group position={[0, 0.333, 0]} rotation={[Math.PI, 0, Math.PI]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.立方体004.geometry}
						material={materials.BedBody}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.立方体004_1.geometry}
						material={materials.BedLeg}
					/>
				</group>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ベッドクッション.geometry}
					material={materials.Cushion}
					position={[0.139, 0.586, 0.107]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ベッド掛け布団.geometry}
					material={materials.Comforter}
					position={[0, 0.333, 0]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ベッド枕.geometry}
					material={materials.Cushion}
					position={[-0.019, 0.586, 0.636]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
			</group>
			<group position={[1.175, 0, 0.92]} rotation={[0, -Math.PI / 2, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Synthesizer001.geometry}
					material={materials.Synthesizer}
					position={[0, 0.635, 0]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.KeyboardStand.geometry}
					material={materials.SyntheStand}
					rotation={[Math.PI, 0, Math.PI]}
				/>
			</group>
			<group position={[-1.328, 0.198, -1.198]}>
				<group
					position={[0, 0.153, 0]}
					rotation={[-3.11, 0.365, -3.096]}
					scale={0.258}
				>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ベジエカーブ006.geometry}
						material={materials.EucalyptusTrunk}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ベジエカーブ006_1.geometry}
						material={materials.EucalyptusLeaf}
					/>
				</group>
				<group position={[0, 0.152, 0]} scale={0.099}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.円柱_1.geometry}
						material={materials.Planter}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.円柱_2.geometry}
						material={materials.Soil}
					/>
				</group>
			</group>
			<group position={[-0.906, 0.806, 1.225]} rotation={[-2.903, 0, -Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面012.geometry}
					material={materials.PC_Body}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面012_1.geometry}
					material={materials.PC_Screen}
				/>
			</group>
			<group position={[-0.906, 0.811, 1.125]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面010.geometry}
					material={materials.PC_Body}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面010_1.geometry}
					material={materials["マテリアル.003"]}
				/>
			</group>
			<group position={[-0.103, 0, 0.104]} rotation={[Math.PI, 0, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WoodFloor001.geometry}
					material={materials["Floor.001"]}
					position={[-0.861, 0, 0.38]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.AcousticGuitar_1.geometry}
				material={materials.AcousticGuitar}
				position={[1.096, 0.267, 0.312]}
				rotation={[-2.537, -0.811, -2.63]}
			/>
		</group>
	);
}

useGLTF.preload("/portfolio_room_1_1.glb");
