/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

生成後に手を入れているので、gltfjsx で作り直したときは以下をやり直すこと。
- Wall の描画を削除 … 窓の開口を持つ RoomWalls に置き換えたため
- 観葉植物（茎・葉・鉢・土）の描画を削除 … 葉が光を受けないため Eucalyptus に置き換えたため
- 各オブジェクトを DropIn で包む … 出現アニメーションを個別に効かせるため
*/

import { DropIn } from "@/components/3d/DropIn";
import { useAvatarMotion } from "@/hooks/useAvatarMotion";
import { CHAIR_PLACEMENTS } from "@/lib/avatarMotion";
import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three/examples/jsm/Addons.js";

type GLTFResult = GLTF & {
	nodes: {
		Wall: THREE.Mesh;
		平面: THREE.Mesh;
		平面_1: THREE.Mesh;
		ローチェア: THREE.Mesh;
		AcousticGuitar_1: THREE.Mesh;
		Chair: THREE.Mesh;
		Desk_1: THREE.Mesh;
		Shelf: THREE.Mesh;
		立方体004: THREE.Mesh;
		立方体004_1: THREE.Mesh;
		ベッドクッション: THREE.Mesh;
		ベッド掛け布団: THREE.Mesh;
		ベッド枕: THREE.Mesh;
		Synthesizer001: THREE.Mesh;
		KeyboardStand: THREE.Mesh;
		ベジエカーブ006: THREE.Mesh;
		ベジエカーブ006_1: THREE.Mesh;
		円柱_1: THREE.Mesh;
		円柱_2: THREE.Mesh;
		平面012: THREE.Mesh;
		平面012_1: THREE.Mesh;
		平面010: THREE.Mesh;
		平面010_1: THREE.Mesh;
		WoodFloor001: THREE.Mesh;
	};
	materials: {
		Wall: THREE.MeshStandardMaterial;
		モニターボディ: THREE.MeshStandardMaterial;
		PC_Screen: THREE.MeshPhysicalMaterial;
		"Guitar_spruce.001": THREE.MeshStandardMaterial;
		AcousticGuitar: THREE.MeshStandardMaterial;
		Chair: THREE.MeshStandardMaterial;
		Desk: THREE.MeshStandardMaterial;
		BedBody: THREE.MeshStandardMaterial;
		BedLeg: THREE.MeshStandardMaterial;
		Cushion: THREE.MeshStandardMaterial;
		Comforter: THREE.MeshStandardMaterial;
		Synthesizer: THREE.MeshStandardMaterial;
		SyntheStand: THREE.MeshStandardMaterial;
		EucalyptusTrunk: THREE.MeshStandardMaterial;
		EucalyptusLeaf: THREE.MeshBasicMaterial;
		Planter: THREE.MeshStandardMaterial;
		Soil: THREE.MeshStandardMaterial;
		PC_Body: THREE.MeshStandardMaterial;
		"マテリアル.003": THREE.MeshStandardMaterial;
		"Floor.001": THREE.MeshPhysicalMaterial;
	};
};

export function Room(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("/portfolio_room_1_1.glb") as unknown as GLTFResult;
	// 椅子はアバターが座るかどうかで置き場所が変わるので、モーションに追従させる
	const chair = CHAIR_PLACEMENTS[useAvatarMotion()];
	return (
		<group {...props} dispose={null}>
			{/* モニター。位置と向きは Portfolio2025-Room.blend の Monitor に合わせてある */}
			<DropIn objectKey="monitor">
				<group position={[-0.387, 1.111, 1.269]} rotation={[0, 0.1484, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.平面.geometry}
						material={materials.モニターボディ}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.平面_1.geometry}
						material={materials.PC_Screen}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="stool">
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ローチェア.geometry}
					material={materials["Guitar_spruce.001"]}
					position={[-1.325, 0.076, -1.208]}
					rotation={[Math.PI, -0.841, Math.PI]}
					scale={[0.15, 0.022, 0.15]}
				/>
			</DropIn>
			<DropIn objectKey="chair">
				<group position={chair.position} rotation={chair.rotation}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Chair.geometry}
						material={materials.Chair}
						position={[0, 0.409, -0.043]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="desk">
				<group position={[-0.616, 0, 1.205]} rotation={[Math.PI, 0, Math.PI]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Desk_1.geometry}
						material={materials.Desk}
						position={[0, 0.8, 0]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="shelf">
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Shelf.geometry}
					material={materials["Guitar_spruce.001"]}
					position={[-0.847, 0.469, -1.209]}
					rotation={[Math.PI, 0, Math.PI]}
				/>
			</DropIn>
			<DropIn objectKey="bed">
				<group position={[0.477, 0, -0.89]} rotation={[0, Math.PI / 2, 0]}>
					<group position={[0, 0.333, 0]} rotation={[Math.PI, 0, Math.PI]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.立方体004.geometry}
							material={materials.BedBody}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.立方体004_1.geometry}
							material={materials.BedLeg}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ベッドクッション.geometry}
						material={materials.Cushion}
						position={[0.139, 0.586, 0.107]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ベッド掛け布団.geometry}
						material={materials.Comforter}
						position={[0, 0.333, 0]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ベッド枕.geometry}
						material={materials.Cushion}
						position={[-0.019, 0.586, 0.636]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="synthesizer">
				<group position={[1.175, 0, 0.92]} rotation={[0, -Math.PI / 2, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Synthesizer001.geometry}
						material={materials.Synthesizer}
						position={[0, 0.635, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.KeyboardStand.geometry}
						material={materials.SyntheStand}
						rotation={[Math.PI, 0, Math.PI]}
					/>
				</group>
			</DropIn>
			{/*
				ノートPC。glb では本体と画面が別オブジェクトのまま書き出されているので、
				ひとつにまとめて Portfolio2025-Room.blend の Laptop の位置・向きに置く。
			*/}
			<DropIn objectKey="laptop">
				<group position={[-0.836, 0.81, 1.179]} rotation={[0, -0.5643, 0]}>
					<group position={[0, -0.005, 0.1]} rotation={[-2.903, 0, -Math.PI]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.平面012.geometry}
							material={materials.PC_Body}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.平面012_1.geometry}
							material={materials.PC_Screen}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.平面010.geometry}
						material={materials.PC_Body}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.平面010_1.geometry}
						material={materials["マテリアル.003"]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="rug">
				<group position={[-0.103, 0, 0.104]} rotation={[Math.PI, 0, Math.PI]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.WoodFloor001.geometry}
						material={materials["Floor.001"]}
						position={[-0.861, 0, 0.38]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="guitar">
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.AcousticGuitar_1.geometry}
					material={materials.AcousticGuitar}
					position={[0.95, 0.267, 0.312]}
					rotation={[-2.0, -1.1, -2.0]}
				/>
			</DropIn>
		</group>
	);
}

useGLTF.preload("/portfolio_room_1_1.glb");
