/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import React, { type JSX, useEffect, useRef } from "react";
import type * as THREE from "three";
import { type GLTF, SkeletonUtils } from "three/examples/jsm/Addons.js";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

type GLTFResult = GLTF & {
	nodes: {
		平面: THREE.Mesh;
		はしご: THREE.Mesh;
		平面_1: THREE.Mesh;
		平面_2: THREE.Mesh;
		ベッド: THREE.Mesh;
		ベッド掛け布団: THREE.Mesh;
		ベッドクッション: THREE.Mesh;
		ベッド枕: THREE.Mesh;
		ローチェア: THREE.Mesh;
		円柱011: THREE.Mesh;
		AcousticGuitar_1: THREE.Mesh;
		Synthesizer_1: THREE.Mesh;
		WoodFloor_1: THREE.Mesh;
		Chair: THREE.Mesh;
		Desk_1: THREE.Mesh;
		ベジエカーブ006: THREE.Mesh;
		ベジエカーブ006_1: THREE.Mesh;
		Book: THREE.Mesh;
		Shelf: THREE.Mesh;
		平面012: THREE.Mesh;
		平面012_1: THREE.Mesh;
		平面010: THREE.Mesh;
		平面010_1: THREE.Mesh;
		円柱002: THREE.Mesh;
	};
	materials: {
		はしご: THREE.MeshPhysicalMaterial;
		モニターボディ: THREE.MeshStandardMaterial;
		モニタースクリーン: THREE.MeshStandardMaterial;
		掛け布団tmp: THREE.MeshStandardMaterial;
		"Guitar_spruce.001": THREE.MeshStandardMaterial;
		ACGuitar: THREE.MeshStandardMaterial;
		Synthesizer: THREE.MeshStandardMaterial;
		Floor: THREE.MeshPhysicalMaterial;
		Chair: THREE.MeshStandardMaterial;
		Desk: THREE.MeshStandardMaterial;
		ユーカリ幹: THREE.MeshStandardMaterial;
		マテリアル: THREE.MeshStandardMaterial;
		PC_Body: THREE.MeshStandardMaterial;
		PC_Screen: THREE.MeshStandardMaterial;
		"マテリアル.003": THREE.MeshStandardMaterial;
		SyntheStand: THREE.MeshStandardMaterial;
	};
};

export function RoomPrototype(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/room-prototype.glb",
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面.geometry}
				material={nodes.平面.material}
				position={[0.384, 0, 0.065]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.はしご.geometry}
				material={materials.はしご}
				position={[1.453, -0.002, -1.238]}
				rotation={[0, 1.571, 0]}
			/>
			<group
				position={[-0.401, 1.11, 1.66]}
				rotation={[Math.PI / 2, 0, Math.PI]}
				scale={[0.62, 1, 0.36]}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面_1.geometry}
					material={materials.モニターボディ}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面_2.geometry}
					material={materials.モニタースクリーン}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ベッド.geometry}
				material={nodes.ベッド.material}
				position={[1.231, 0.333, 0.871]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ベッド掛け布団.geometry}
				material={materials.掛け布団tmp}
				position={[1.231, 0.333, 0.871]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ベッドクッション.geometry}
				material={nodes.ベッドクッション.material}
				position={[1.37, 0.586, 0.978]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ベッド枕.geometry}
				material={nodes.ベッド枕.material}
				position={[1.212, 0.586, 1.508]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ローチェア.geometry}
				material={materials["Guitar_spruce.001"]}
				position={[-1.024, 0.177, -1.352]}
				rotation={[Math.PI, -0.841, Math.PI]}
				scale={[0.15, 0.022, 0.15]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱011.geometry}
				material={materials["Guitar_spruce.001"]}
				position={[-0.653, 0.45, -1.53]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={[0.15, 0.022, 0.15]}
			/>
			<group position={[-0.016, 0, 0.065]} rotation={[Math.PI, 0, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WoodFloor_1.geometry}
					material={materials.Floor}
					position={[-0.4, 0, 0]}
				/>
			</group>
			<group position={[-0.45, 0, 1.162]} rotation={[0, -0.814, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Chair.geometry}
					material={materials.Chair}
					position={[0, 0.409, -0.043]}
				/>
			</group>
			<group position={[-0.616, 0, 1.565]} rotation={[Math.PI, 0, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Desk_1.geometry}
					material={materials.Desk}
					position={[0, 0.8, 0]}
				/>
			</group>
			<group
				position={[-0.268, 0.158, -1.416]}
				rotation={[-3.11, 0.365, -3.096]}
				scale={0.258}
			>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ベジエカーブ006.geometry}
					material={materials.ユーカリ幹}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.ベジエカーブ006_1.geometry}
					material={materials.マテリアル}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book.geometry}
				material={nodes.Book.material}
				position={[-1.823, 0.666, -1.627]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf.geometry}
				material={materials["Guitar_spruce.001"]}
				position={[-1.566, 0.469, -1.555]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<group position={[-0.906, 0.815, 1.587]} rotation={[-2.903, 0, -Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面012.geometry}
					material={materials.PC_Body}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面012_1.geometry}
					material={materials.PC_Screen}
				/>
			</group>
			<group position={[-0.906, 0.82, 1.485]} rotation={[Math.PI, 0, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面010.geometry}
					material={materials.PC_Body}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面010_1.geometry}
					material={materials["マテリアル.003"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱002.geometry}
				material={materials.SyntheStand}
				position={[0.492, 0, -1.534]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.AcousticGuitar_1.geometry}
				material={materials.ACGuitar}
				position={[0.61, 0.267, 0.623]}
				rotation={[-1.845, -1.152, -1.823]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Synthesizer_1.geometry}
				material={materials.Synthesizer}
				position={[0.487, 0.636, -1.54]}
			/>
		</group>
	);
}

useGLTF.preload("/room-prototype.glb");
