/*
Auto-generated by: https://github.com/pmndrs/gltfjsx

生成後に手を入れているので、gltfjsx で作り直したときは以下をやり直すこと。
- 壁と壁掛け時計の描画を削除 … RoomWalls と WallClock が同じ glb から描くため
- 各オブジェクトを DropIn で包む … 出現アニメーションを個別に効かせるため
- 椅子の位置をモーションに追従させる
- castShadow / receiveShadow を付ける

位置と向きは Portfolio2025-Room.blend が持っている値がそのまま出てくる。
配置を変えたいときはここではなく .blend を直し、glb を書き出し直すこと。
*/

import { DropIn } from "@/components/3d/DropIn";
import { useAvatarMotion } from "@/hooks/useAvatarMotion";
import { CHAIR_PLACEMENTS } from "@/lib/avatarMotion";
import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three/examples/jsm/Addons.js";

export const ROOM_GLB = "/portfolio_room_1_2.glb";

export type RoomGLTF = GLTF & {
	nodes: {
		AcousticGuitarBody: THREE.Mesh;
		ChairBody: THREE.Mesh;
		DeskBody: THREE.Mesh;
		BedFrame_1: THREE.Mesh;
		BedFrame_2: THREE.Mesh;
		BedCushion: THREE.Mesh;
		BedComforter: THREE.Mesh;
		BedPillow: THREE.Mesh;
		SynthesizerBody: THREE.Mesh;
		SynthesizerStand: THREE.Mesh;
		WoodFloorBody: THREE.Mesh;
		EucalyptusFoliage_1: THREE.Mesh;
		EucalyptusFoliage_2: THREE.Mesh;
		Planter_1: THREE.Mesh;
		Planter_2: THREE.Mesh;
		LaptopBody_1: THREE.Mesh;
		LaptopBody_2: THREE.Mesh;
		LaptopBody_3: THREE.Mesh;
		MonitorBody_1: THREE.Mesh;
		MonitorBody_2: THREE.Mesh;
		WallGreen: THREE.Mesh;
		WallWhite: THREE.Mesh;
		WindowFrame: THREE.Mesh;
		WindowSky: THREE.Mesh;
		StoolBody: THREE.Mesh;
		WavyShelfBody: THREE.Mesh;
		ClockCase: THREE.Mesh;
		ClockFace: THREE.Mesh;
		ClockMarks: THREE.Mesh;
		ClockHourHand: THREE.Mesh;
		ClockMinuteHand: THREE.Mesh;
	};
	materials: {
		AcousticGuitar: THREE.MeshStandardMaterial;
		Chair: THREE.MeshStandardMaterial;
		Desk: THREE.MeshStandardMaterial;
		BedBody: THREE.MeshStandardMaterial;
		BedLeg: THREE.MeshStandardMaterial;
		Cushion: THREE.MeshStandardMaterial;
		Comforter: THREE.MeshStandardMaterial;
		Synthesizer: THREE.MeshStandardMaterial;
		SynthesizerStand: THREE.MeshStandardMaterial;
		WoodFloorTop: THREE.MeshPhysicalMaterial;
		EucalyptusTrunk: THREE.MeshStandardMaterial;
		EucalyptusLeaf: THREE.MeshStandardMaterial;
		Planter: THREE.MeshStandardMaterial;
		Soil: THREE.MeshStandardMaterial;
		LaptopBody: THREE.MeshStandardMaterial;
		LaptopKeyboard: THREE.MeshStandardMaterial;
		LaptopScreen: THREE.MeshPhysicalMaterial;
		MonitorBody: THREE.MeshStandardMaterial;
		MonitorScreen: THREE.MeshPhysicalMaterial;
		WallGreen: THREE.MeshStandardMaterial;
		WallWhite: THREE.MeshStandardMaterial;
		WindowFrame: THREE.MeshStandardMaterial;
		WindowSky: THREE.MeshStandardMaterial;
		StoolWood: THREE.MeshStandardMaterial;
		WavyShelf: THREE.MeshStandardMaterial;
		ClockCase: THREE.MeshStandardMaterial;
		ClockFace: THREE.MeshStandardMaterial;
		ClockHand: THREE.MeshStandardMaterial;
	};
};

export function Room(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(ROOM_GLB) as unknown as RoomGLTF;
	// 椅子はアバターが座るかどうかで置き場所が変わるので、モーションに追従させる
	const chair = CHAIR_PLACEMENTS[useAvatarMotion()];
	return (
		<group {...props} dispose={null}>
			<DropIn objectKey="chair">
				<group position={chair.position} rotation={chair.rotation}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.ChairBody.geometry}
						material={materials.Chair}
						position={[0, 0.409, -0.043]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="desk">
				<group position={[-0.616, 0, 1.205]} rotation={[Math.PI, 0, Math.PI]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.DeskBody.geometry}
						material={materials.Desk}
						position={[0, 0.8, 0]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="bed">
				<group position={[0.477, 0, -0.89]} rotation={[0, Math.PI / 2, 0]}>
					<group position={[0, 0.333, 0]} rotation={[Math.PI, 0, Math.PI]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.BedFrame_1.geometry}
							material={materials.BedBody}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.BedFrame_2.geometry}
							material={materials.BedLeg}
						/>
					</group>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BedCushion.geometry}
						material={materials.Cushion}
						position={[0.139, 0.586, 0.107]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BedComforter.geometry}
						material={materials.Comforter}
						position={[0, 0.333, 0]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.BedPillow.geometry}
						material={materials.Cushion}
						position={[-0.019, 0.586, 0.636]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="synthesizer">
				<group position={[1.175, 0, 0.92]} rotation={[0, -Math.PI / 2, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.SynthesizerBody.geometry}
						material={materials.Synthesizer}
						position={[0, 0.635, 0]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.SynthesizerStand.geometry}
						material={materials.SynthesizerStand}
						rotation={[Math.PI, 0, Math.PI]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="rug">
				<group position={[-0.103, 0, 0.104]} rotation={[Math.PI, 0, Math.PI]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.WoodFloorBody.geometry}
						material={materials.WoodFloorTop}
						position={[-0.861, 0, 0.38]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="eucalyptus">
				<group position={[-1.327, 0.199, -1.192]} rotation={[-Math.PI, 0.865, -Math.PI]}>
					<group position={[0, 0.153, 0]} rotation={[-3.11, 0.365, -3.096]} scale={0.258}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.EucalyptusFoliage_1.geometry}
							material={materials.EucalyptusTrunk}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.EucalyptusFoliage_2.geometry}
							material={materials.EucalyptusLeaf}
						/>
					</group>
					<group position={[0, 0.152, 0]} scale={0.099}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Planter_1.geometry}
							material={materials.Planter}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Planter_2.geometry}
							material={materials.Soil}
						/>
					</group>
				</group>
			</DropIn>
			<DropIn objectKey="laptop">
				<group position={[-0.836, 0.81, 1.179]} rotation={[0, -0.564, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.LaptopBody_1.geometry}
						material={materials.LaptopBody}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.LaptopBody_2.geometry}
						material={materials.LaptopKeyboard}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.LaptopBody_3.geometry}
						material={materials.LaptopScreen}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="monitor">
				<group position={[-0.387, 0.801, 1.269]} rotation={[0, 0.148, 0]}>
					<group position={[0, 0.31, 0]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.MonitorBody_1.geometry}
							material={materials.MonitorBody}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.MonitorBody_2.geometry}
							material={materials.MonitorScreen}
						/>
					</group>
				</group>
			</DropIn>
			<DropIn objectKey="stool">
				<group position={[-1.328, 0, -1.206]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.StoolBody.geometry}
						material={materials.StoolWood}
						position={[0, 0.077, 0]}
						rotation={[Math.PI, -0.841, Math.PI]}
						scale={[0.15, 0.022, 0.15]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="shelf">
				<group position={[-0.849, 0, -1.2]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.WavyShelfBody.geometry}
						material={materials.WavyShelf}
						position={[0, 0.469, 0]}
						rotation={[Math.PI, 0, Math.PI]}
					/>
				</group>
			</DropIn>
			<DropIn objectKey="guitar">
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.AcousticGuitarBody.geometry}
					material={materials.AcousticGuitar}
					position={[0.95, 0.267, 0.312]}
					rotation={[1.829, 0.738, 1.829]}
				/>
			</DropIn>
		</group>
	);
}

useGLTF.preload(ROOM_GLB);
